name: CI-CD workflow

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: namn här
    runs-on: ubuntu-latest

    steps:
      - name: Hämta kod
        uses: actions/checkout@v4

      - name: hämtar Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Gör maven wrapper körbar
        run: chmod +x ./mvnw

#      - name: kör test
#        run: ./mvnw -B tests

      - name: Bygg applikationen utan att köra tester igen
        run: ./mvnw -B -DskipTests clean package

      - name: Skapa surefire rapporter
        uses: actions/upload-artifact@v4
        with:
          name: user-registration-api-jar
          path: target/user-registration-api-*.jar
          if-no-files-found: error

  test:
    name: Kör automatiska tester
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Hämta koden
        uses: actions/checkout@v4

      - name: Hämta Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Gör maven körbar
        run: chmod +x ./mvnw

      - name: kör tester
        run: ./mvnw -B test

      - name: Ladda upp surefire rapporter
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: target/surefire-reports/
          if-no-files-found: warn

  deploy:
    name: Simulerad deploy till staging
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.event_name=='push' && github.ref=='refs/heads/main'
    environment: staging

    steps:
      - name: Hämta byggresultat
        uses: actions/download-artifact@v4
        with:
          name: user-registration-api-jar
          path: deploy

      - name: Visa vad som skulle deployas
        run: |
          echo "Alla tester ät godkända på main"
          echo "Simulerar deploy till staging"
          ls-lh deploy
          echo "En verklig deploy skulle använda miljöns säkra credentials"
